DROP TABLE CHK_PLT.LICENSE_PLATE_STAGING CASCADE CONSTRAINTS;

CREATE TABLE CHK_PLT.LICENSE_PLATE_STAGING
(
  PLATE_NUMBER        VARCHAR2(25 BYTE)         NOT NULL,
  PLATE_ADDRESS       VARCHAR2(250 BYTE)        NOT NULL,
  PLATE_CITY          VARCHAR2(60 BYTE)         NOT NULL,
  PLATE_STATE         VARCHAR2(2 BYTE)          NOT NULL,
  PLATE_ZIP           VARCHAR2(5 BYTE)          NOT NULL,
  VEHICLE_TYPE        VARCHAR2(25 BYTE),
  VEHICLE_CLASS       VARCHAR2(25 BYTE),
  CREATED_DATE        DATE                      NOT NULL,
  CREATED_TXN_ID      NUMBER(15)                NOT NULL,
  GEO_PROCESSED       NUMBER(15)                DEFAULT 0                     NOT NULL,
  IN_DISTRICT         NUMBER(15)                DEFAULT 0                     NOT NULL,
  GEOCODED            NUMBER(15)                DEFAULT 0                     NOT NULL,
  GEO_MODIFIED_DATE   DATE,
  DS_MODIFIED_DATE    DATE,
  DS_MODIFIED_TXN_ID  NUMBER(15)
)
TABLESPACE PLT_DIR_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN CHK_PLT.LICENSE_PLATE_STAGING.CREATED_DATE IS 'DS process creates the record';

COMMENT ON COLUMN CHK_PLT.LICENSE_PLATE_STAGING.CREATED_TXN_ID IS 'Initial Transaction Id from DMV File';

COMMENT ON COLUMN CHK_PLT.LICENSE_PLATE_STAGING.GEO_PROCESSED IS 'RTD GEO Process Flag';

COMMENT ON COLUMN CHK_PLT.LICENSE_PLATE_STAGING.IN_DISTRICT IS 'In-Out District Flag';

COMMENT ON COLUMN CHK_PLT.LICENSE_PLATE_STAGING.DS_MODIFIED_TXN_ID IS 'Last Transaction Id from DMV File';



GRANT SELECT ON CHK_PLT.LICENSE_PLATE_STAGING TO CHKPLT_DEV;
GRANT SELECT ON CHK_PLT.LICENSE_PLATE_STAGING TO CHKPLT_DS;
